baseURL = "https://devletters.com/"
languageCode = "en-us"
title = "Dev Letters"
theme = "capsule"
SectionPagesMenu = "main"
disqusShortname = "devletters"

[author]
  name = "Avi Aryan"
  image = "https://aviaryan.github.io/hosting/scary%20dark%20256.jpg"

[params]
  googleAnalytics = "UA-42460130-5"
  description = "Frequent emails about various aspects of life as a freelance developer and a startup person. Join today for free and learn a new thing with every email."
  keywords = "Newsletter,Coder,Developer,Coding,Freelance,Startup,Blog,Avi Aryan"
  subs = "350"

[social]
  twitter = "aviaryan123"
  facebook = "aviaryan123"

[taxonomies]
  tag = "tags"
  category = "categories"
