baseURL = "https://devletters.com/"
languageCode = "en-us"
title = "Dev Letters"
theme = "capsule"
SectionPagesMenu = "main"
disqusShortname = "devletters"

[author]
  name = "Avi Aryan"
  image = "https://aviaryan.github.io/hosting/scary%20dark%20256.jpg"

[params]
  googleAnalytics = "UA-42460130-5"
  description = "Mailing list about various aspects of life as a developer. Maintained by Avi Aryan."
  keywords = "Newsletter,Coder,Developer,Coding,Freelance,Startup,Blog,Avi Aryan"
  subs = "130"

[social]
  twitter = "aviaryan123"
  facebook = "aviaryan123"

[taxonomies]
  tag = "tags"
  category = "categories"
