baseURL = "https://devletters.com/"
languageCode = "en-us"
title = "Dev Letters"
theme = "capsule"
SectionPagesMenu = "main"

[author]
  name = "Avi Aryan"

[params]
  googleAnalytics = "UA-42460130-5"
  description = "Mailing list about various aspects of life as a developer. Maintained by Avi Aryan."

[social]
  twitter = "aviaryan123"
  facebook = "aviaryan123"

#[taxonomies]
#  category = "categories"
#  tag = "tags"
