baseURL = "https://devletters.com/"
languageCode = "en-us"
title = "Dev Letters"
description = "Letters from a Developer"
theme = "capsule"
SectionPagesMenu = "main"

[author]
  name = "Avi Aryan"

[params]
  googleAnalytics = "UA-42460130-5"

[social]
  twitter = "aviaryan123"
  facebook = "aviaryan123"

[taxonomies]
  category = "categories"
  tag = "tags"
